<<<<<<< HEAD
name: SkeletonAPI
version: 0.1.0.0
github: "githubuser/SkeletonAPI"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/SkeletonAPI#readme>

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - warp
  - wai
  - aeson
  - text
  - bytestring
  - process
  - directory

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
    - Paths_SkeletonAPI

executables:
  ServantAPISkeletonExe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - servant
      - servant-server
      - warp
      - wai
      - aeson
      - text
      - base
      - SkeletonAPI
    other-modules:
      - Paths_SkeletonAPI

tests:
  SkeletonAPITest:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - servant
      - servant-server
      - warp
      - wai
      - aeson
      - text
      - hspec
      - SkeletonAPI
    other-modules:
      - Paths_SkeletonAPI
=======
name: SkeletonAPI
version: 0.1.0.0
github: "githubuser/SkeletonAPI"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/SkeletonAPI#readme>

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - warp
  - wai
  - aeson
  - text
  - bytestring
  - process
  - directory

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
    - Paths_SkeletonAPI

executables:
  ServantAPISkeletonExe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - servant
      - servant-server
      - warp
      - wai
      - aeson
      - text
      - base
      - SkeletonAPI
    other-modules:
      - Paths_SkeletonAPI

tests:
  SkeletonAPITest:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - servant
      - servant-server
      - warp
      - wai
      - aeson
      - text
      - hspec
      - SkeletonAPI
    other-modules:
      - Paths_SkeletonAPI
>>>>>>> ce9af146ce06abdf0e406970988b4dad0a069acd
